SELECT 
    c.EMAIL AS CLIENTE_EMAIL,
    c.NOMBRE AS CLIENTE_NOMBRE,
    c.DIRECCION AS CLIENTE_DIRECCION,
    
    p.ID_PEDIDO,
    p.FECHA AS PEDIDO_FECHA,
    p.TOTAL AS PEDIDO_TOTAL,
    p.DESTINO AS PEDIDO_DESTINO,
    p.ESTADO AS PEDIDO_ESTADO,
    
    f.EMAIL AS FLORICULTOR_EMAIL,
    f.NOMBRE AS FLORICULTOR_NOMBRE,
    f.UBICACION AS FLORICULTOR_UBICACION,
    f.DISPONIBILIDAD AS FLORICULTOR_DISPONIBILIDAD,
    
    pr.ID_PRODUCTO,
    pr.NOMBRE AS PRODUCTO_NOMBRE,
    pr.TIPO_FLOR AS PRODUCTO_TIPO_FLOR,
    pr.PRECIO AS PRODUCTO_PRECIO,
    
    dp.ID_DETALLE,
    dp.CANTIDAD AS DETALLE_CANTIDAD,
    dp.SUBTOTAL AS DETALLE_SUBTOTAL
    
FROM PEDIDO p
JOIN CLIENTE c ON p.EMAIL_CLIENTE = c.EMAIL
JOIN FLORICULTOR f ON p.EMAIL_FLORICULTOR = f.EMAIL
JOIN DETALLE_PEDIDO dp ON p.ID_PEDIDO = dp.ID_PEDIDO
JOIN PRODUCTO pr ON dp.ID_PRODUCTO = pr.ID_PRODUCTO AND pr.EMAIL_FLORICULTOR = f.EMAIL;